# coding=utf8
# the above tag defines encoding for this document and is for Python 2.x compatibility

import re

regex = r"\"Cubic Centimeters\">(.*?)</td>"

test_str = ("<table>\n"
	"            <thead>\n"
	"                <tr>\n"
	"                    <th>Liters (L)</th>\n"
	"                    <th>Cubic Centimeters (CC)</th>\n"
	"                    <th>Cubic Inches (CID)</th>\n"
	"                </tr>\n"
	"            </thead>\n"
	"            <tbody>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">1.0</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">1,000</td>\n"
	"                    <td data-th=\"Cubic Inches\">61</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">1.5</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">1,500</td>\n"
	"                    <td data-th=\"Cubic Inches\">92</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">1.6</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">1,606</td>\n"
	"                    <td data-th=\"Cubic Inches\">98</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">1.7</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">1,721</td>\n"
	"                    <td data-th=\"Cubic Inches\">105</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">1.8</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">1,836</td>\n"
	"                    <td data-th=\"Cubic Inches\">112</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">2.0</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">1,983</td>\n"
	"                    <td data-th=\"Cubic Inches\">121</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">2.0</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">2,000</td>\n"
	"                    <td data-th=\"Cubic Inches\">122</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">2.2</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">2,196</td>\n"
	"                    <td data-th=\"Cubic Inches\">134</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">2.2</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">2,213</td>\n"
	"                    <td data-th=\"Cubic Inches\">135</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">2.3</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">2,295</td>\n"
	"                    <td data-th=\"Cubic Inches\">140</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">2.5</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">2,475</td>\n"
	"                    <td data-th=\"Cubic Inches\">151</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">2.6</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">2,557</td>\n"
	"                    <td data-th=\"Cubic Inches\">156</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">2.6</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">2,606</td>\n"
	"                    <td data-th=\"Cubic Inches\">159</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">2.8</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">2,786</td>\n"
	"                    <td data-th=\"Cubic Inches\">170</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">2.8</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">2,803</td>\n"
	"                    <td data-th=\"Cubic Inches\">171</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">2.8</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">2,835</td>\n"
	"                    <td data-th=\"Cubic Inches\">173</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">3.0</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">2,967</td>\n"
	"                    <td data-th=\"Cubic Inches\">181</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">3.2</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">3,212</td>\n"
	"                    <td data-th=\"Cubic Inches\">196</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">3.3</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">3,278</td>\n"
	"                    <td data-th=\"Cubic Inches\">200</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">3.5</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">3,475</td>\n"
	"                    <td data-th=\"Cubic Inches\">212</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">3.7</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">3,688</td>\n"
	"                    <td data-th=\"Cubic Inches\">225</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">3.8</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">3,753</td>\n"
	"                    <td data-th=\"Cubic Inches\">229</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">3.8</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">3,786</td>\n"
	"                    <td data-th=\"Cubic Inches\">231</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">3.8</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">3,802</td>\n"
	"                    <td data-th=\"Cubic Inches\">232</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">3.9</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">3,901</td>\n"
	"                    <td data-th=\"Cubic Inches\">238</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">4.1</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">4,097</td>\n"
	"                    <td data-th=\"Cubic Inches\">250</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">4.1</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">4,130</td>\n"
	"                    <td data-th=\"Cubic Inches\">252</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">4.2</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">4,179</td>\n"
	"                    <td data-th=\"Cubic Inches\">255</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">4.2</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">4,229</td>\n"
	"                    <td data-th=\"Cubic Inches\">258</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">4.3</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">4,261</td>\n"
	"                    <td data-th=\"Cubic Inches\">260</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">4.3</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">4,343</td>\n"
	"                    <td data-th=\"Cubic Inches\">265</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">4.4</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">4,376</td>\n"
	"                    <td data-th=\"Cubic Inches\">267</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">4.8</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">4,786</td>\n"
	"                    <td data-th=\"Cubic Inches\">292</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">4.9</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">4,917</td>\n"
	"                    <td data-th=\"Cubic Inches\">300</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">4.9</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">4,933</td>\n"
	"                    <td data-th=\"Cubic Inches\">301</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">5.0</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">4,949</td>\n"
	"                    <td data-th=\"Cubic Inches\">302</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">5.0</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">4,983</td>\n"
	"                    <td data-th=\"Cubic Inches\">304</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">5.0</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">4,999</td>\n"
	"                    <td data-th=\"Cubic Inches\">305</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">5.0</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">5,032</td>\n"
	"                    <td data-th=\"Cubic Inches\">307</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">5.2</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">5,212</td>\n"
	"                    <td data-th=\"Cubic Inches\">318</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">5.7</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">5,736</td>\n"
	"                    <td data-th=\"Cubic Inches\">350</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">5.8</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">5,753</td>\n"
	"                    <td data-th=\"Cubic Inches\">351</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">5.9</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">5,884</td>\n"
	"                    <td data-th=\"Cubic Inches\">359</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">5.9</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">5,900</td>\n"
	"                    <td data-th=\"Cubic Inches\">360</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">6.0</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">6,032</td>\n"
	"                    <td data-th=\"Cubic Inches\">368</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">6.2</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">6,195</td>\n"
	"                    <td data-th=\"Cubic Inches\">378</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">6.2</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">6,212</td>\n"
	"                    <td data-th=\"Cubic Inches\">379</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">6.6</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">6,556</td>\n"
	"                    <td data-th=\"Cubic Inches\">400</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">6.6</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">6,605</td>\n"
	"                    <td data-th=\"Cubic Inches\">403</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">6.9</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">6,884</td>\n"
	"                    <td data-th=\"Cubic Inches\">420</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">7.0</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">6,966</td>\n"
	"                    <td data-th=\"Cubic Inches\">425</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">7.0</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">6,982</td>\n"
	"                    <td data-th=\"Cubic Inches\">426</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">7.4</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">7,447</td>\n"
	"                    <td data-th=\"Cubic Inches\">454</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">7.5</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">7,539</td>\n"
	"                    <td data-th=\"Cubic Inches\">460</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">7.6</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">7,638</td>\n"
	"                    <td data-th=\"Cubic Inches\">466</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">7.8</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">7,785</td>\n"
	"                    <td data-th=\"Cubic Inches\">475</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">8.1</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">8,113</td>\n"
	"                    <td data-th=\"Cubic Inches\">495</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">8.2</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">8,195</td>\n"
	"                    <td data-th=\"Cubic Inches\">500</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">8.3</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">8,261</td>\n"
	"                    <td data-th=\"Cubic Inches\">504</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">8.6</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">8,605</td>\n"
	"                    <td data-th=\"Cubic Inches\">525</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">9.0</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">9,031</td>\n"
	"                    <td data-th=\"Cubic Inches\">551</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">9.0</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">9,047</td>\n"
	"                    <td data-th=\"Cubic Inches\">552</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">9.1</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">9,096</td>\n"
	"                    <td data-th=\"Cubic Inches\">555</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">9.3</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">9,310</td>\n"
	"                    <td data-th=\"Cubic Inches\">568</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">10.0</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">10,014</td>\n"
	"                    <td data-th=\"Cubic Inches\">611</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">10.4</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">10,424</td>\n"
	"                    <td data-th=\"Cubic Inches\">636</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">10.5</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">10,457</td>\n"
	"                    <td data-th=\"Cubic Inches\">638</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">11.0</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">11,014</td>\n"
	"                    <td data-th=\"Cubic Inches\">672</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">11.0</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">11,030</td>\n"
	"                    <td data-th=\"Cubic Inches\">673</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">11.6</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">11,588</td>\n"
	"                    <td data-th=\"Cubic Inches\">707</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">12.0</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">12,036</td>\n"
	"                    <td data-th=\"Cubic Inches\">736</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">12.2</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">12,178</td>\n"
	"                    <td data-th=\"Cubic Inches\">743</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">13.9</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">13,964</td>\n"
	"                    <td data-th=\"Cubic Inches\">852</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">14.0</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">14,013</td>\n"
	"                    <td data-th=\"Cubic Inches\">855</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">14.2</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">14,161</td>\n"
	"                    <td data-th=\"Cubic Inches\">864</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">14.2</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">14,194</td>\n"
	"                    <td data-th=\"Cubic Inches\">866</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">14.6</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">14,636</td>\n"
	"                    <td data-th=\"Cubic Inches\">893</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">14.8</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">14,800</td>\n"
	"                    <td data-th=\"Cubic Inches\">903</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">15.2</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">15,193</td>\n"
	"                    <td data-th=\"Cubic Inches\">927</td>\n"
	"                </tr>\n"
	"                <tr>\n"
	"                    <td data-th=\"Liters\">18.0</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">18,013</td>\n"
	"                    <td data-th=\"Cubic Inches\">1,099</td>\n"
	"                </tr>\n"
	"                <tr class=\"alt\">\n"
	"                    <td data-th=\"Liters\">18.8</td>\n"
	"                    <td data-th=\"Cubic Centimeters\">18,848</td>\n"
	"                    <td data-th=\"Cubic Inches\">1,150</td>\n"
	"                </tr>\n"
	"                </tbody>\n"
	"            </table>")

matches = re.findall(regex, test_str, re.MULTILINE)
a = []
for match in matches:
    a.append(int(match.replace(",","")))
print(a)
